name: shooda_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.0-42.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Translations
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Shooda deps
  picasso:
    path: ../packages/picasso

  # Third party deps
  equatable: ^2.0.0
  get_it: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
