name: flutter_skeleton_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Translations
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Flutter Skeleton App deps
  banksy_ui:
    path: ../packages/banksy_ui

  # Third party deps
  equatable: ^2.0.0
  get_it: ^7.2.0
  form_validator: ^1.0.1
  shared_preferences: ^2.0.9
  dio: ^4.0.0
  provider: ^6.0.1
  firebase_core: "^1.10.0"
  firebase_analytics: ^8.3.4
  firebase_crashlytics: "^2.3.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
