name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #
      # Install & build app
      #
      - name: Install flutter
        uses: subosito/flutter-action@master
        with:
          channel: stable

      - name: Install
        run: make install

      - name: Localizations
        run: make localizations

      - name: Decrypt GoogleServices config
        working-directory: app/android/app
        run: |
          gpg --quiet --batch --yes --decrypt \
            --passphrase="$FIREBASE_ENCRYPT_SECRET" \
            --output google-services.tar google-services.tar.gpg
          tar xvf google-services.tar
        env:
          FIREBASE_ENCRYPT_SECRET: ${{ secrets.FIREBASE_ENCRYPT_SECRET }}

      - name: Build
        run: flutter build appbundle --verbose --release -t lib/main_prod.dart --build-name=0.0.2
        # run: flutter build appbundle --verbose --release -t lib/main_prod.dart --build-name=${{ github.event.release.tag_name }}
        working-directory: app

      - name: Sign App Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/app/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE_SIGNING_KEY }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Publish to Play Store internal test track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          packageName: com.canastro.flutterskeletonapp
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
          track: internal
          # track: production
          # mappingFile: app/build/app/outputs/mapping/release/mapping.txt
