name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build_ios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt GoogleServices config
        working-directory: app/ios/Runner
        run: |
          gpg
            --quiet \
            --batch \
            --yes \
            --decrypt \
            --passphrase="$FIREBASE_ENCRYPT_SECRET" \
            --output GoogleService-Info.tar GoogleService-Info.tar.gpg
          tar xvf GoogleService-Info.tar

      - name: Decrypt GoogleServices config
        working-directory: app/android/app
        run: |
          gpg
            --quiet \
            --batch \
            --yes \
            --decrypt \
            --passphrase="$FIREBASE_ENCRYPT_SECRET" \
            --output google-services.tar google-services.tar.gpg
          tar xvf google-services.tar
